---
apiVersion: v1
kind: Service
metadata:
  name: awl-test-redis-service
  labels:
    username: awl
    env: test
spec:
  type: ClusterIP
  selector:
    app: awl-test-redis
  ports:
  - name: awl-test-redis
    port: 6379
    targetPort: 6379
