---
apiVersion: v1
kind: Service
metadata:
  name: awl-test-flask-service
  labels:
    username: awl
    env: test
spec:
  type: ClusterIP
  selector:
    app: awl-test-flask
  ports:
  - name: awl-test-flask
    port: 5000
    targetPort: 5000

